-- Auto-generated by socrates.tools.lean_prover
-- DO NOT EDIT MANUALLY (overwritten on each call)


namespace SocratesScratch

theorem sorry_test : (1 : Nat) + 1 = 2 := by
  sorry

end SocratesScratch
